[package]
name = "sword_of_osman"
version = "0.1.0"
authors = ["musaab"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.5.13", features = ["serialization"] }
specs = { version = "0.15.1", features = ["serde"] }
specs-derive = "0.4.0"
serde= { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"